### ISSUE TITLE
[Viz] Viz master issue

### ISSUE THREAD

**Issue by LucasZamprogno** [ubccpsc310/classy#46]
- [x] Add branch selection on team tab
- [ ] Add best fit line to scatterplot (not that easy)
- [x] Add color scheme toggle
- [ ] Make c1/c2 code not awful and support c3
- [x] Get team member names on team page
- [x] Make requests all at once

**Comment by rtholmes** [comment]
Viz no longer deployed.
